"""
Configuration for Shopping & Switching Intelligence.
All thresholds, colours, and settings centralised here.
"""

# Suppression thresholds
MIN_BASE_PUBLISHABLE = 50
MIN_BASE_INDICATIVE = 30
MIN_BASE_FLOW_CELL = 10
MIN_BASE_TREND_PERIOD = 30
MIN_BASE_REASON_PCT = 30
MIN_BASE_CHANNEL = 30
MIN_BASE_PCW = 20
MIN_BASE_NPS = 20
MIN_BASE_SATISFACTION = 20
MIN_BASE_MARKET = 100
MIN_ELIGIBLE_INSURERS_WARNING = 3

# Bayesian smoothing
PRIOR_STRENGTH = 30
TREND_NOISE_THRESHOLD = 2.0  # percentage points
CONFIDENCE_LEVEL = 0.95
Z_SCORE = 1.96

# CI Brand colours
CI_MAGENTA = "#981D97"
CI_YELLOW = "#FFCD00"
CI_GREEN = "#48A23F"
CI_RED = "#F4364C"
CI_BLUE = "#5BC2E7"
CI_GREY = "#54585A"
CI_LIGHT_GREY = "#F2F2F2"

# Visual rules
INSURER_COLOUR = CI_MAGENTA
MARKET_COLOUR = CI_GREY
POSITIVE_GAP_COLOUR = CI_GREEN
NEGATIVE_GAP_COLOUR = CI_RED
NEUTRAL_GAP_THRESHOLD = 1.0  # percentage points
